### ISSUE TITLE
Adapt Pluralsight IQ Questions

### ISSUE THREAD

**Issue by flxwu** [fejes713/30-seconds-of-interviews#13]
At the WeAreDevelopers World Congress in Vienna, I tried out the Pluralsight IQ tests several times - and the questions were really well-thought and well-chosen. 
I think we could adapt at least some of them :+1:

**Comment by skatcat31** [comment]
I went through the JS test at least... I'm not certain I like a few of their questions(they're kind of outdated), but a lot of them would be great to adapt

**Comment by fejes713** [comment]
I have added Pluralsight questions to the new branch `pluralsight-questions`. Those are just questions with no answers. We can slowly start adding answers to them, no rush.

Those questions can be answered in one or two sentences but I would like to keep answers rich like we do in the rest of the project so feel free to mention relevant information in each answer.

Here's the branch: https://github.com/fejes713/30-seconds-of-interviews/tree/pluralsight-questions

**Comment by skatcat31** [comment]
I think this might be better tackled the same way it was with https://github.com/Chalarangelo/30-seconds-of-code/issues/100

**Comment by fejes713** [comment]
@skatcat31 You're right. I will try to add an issue later today! Thanks

**Comment by theodesp** [comment]
I write questions for Pluralsight IQ and we have to bear in mind that its intellectual property of Pluralsight and the authors that make them and we should not copy them in any way unless we ask for permission. There is a lot of time to prepare those questions so there should be only newly created ones.

**Comment by fejes713** [comment]
Thanks for letting us know about it @theodesp. However, I am not so sure about that statement.

How could question "How do you remove a property from an object?" be a legal property of Pluralsight?

Those are questions that are encountered in every other interview. @skatcat31 @Chalarangelo Could you please revisit this (as well as the rest of the core team)?

**Comment by theodesp** [comment]
I suppose some questions are not. But others with code examples could be.
