### ISSUE TITLE
BackEnd?

### ISSUE THREAD

**Issue by flxwu** [fejes713/30-seconds-of-interviews#24]
Subsequently to #19 and the things we talked about in 30-seconds-of-code, I am thinking about adding a BackEnd. I mean, we don't have to give it full functionality, but we could for sure just set it up and maybe use it to easily try out things like voting. Maybe you guys already discussed it, but What do you think?

We would, of course, thus have to put it on i.e. heroku, but that's not a big deal.

**Comment by imcodingideas** [comment]
I'm really enjoying Hapi right now. The swagger plugin and joi validation are pretty sweet.

**Comment by Chalarangelo** [comment]
@imcodingideas I just found out about Hapi a few days ago. It seems really cool and interesting (and kinda less complex than Express). Might be worth looking into.

**Comment by skatcat31** [comment]
@Chalarangelo express is complex? I always thought express was so un-opinionated that if you didn't know what you were doing you'd quickly go down in flames. I'm not such a fan of Hapi though due to it's really confusing changing returns and awkward handler registration.

The difference is that Hapi is more opinionated which means a lot of things will work, but only work if you do it the way Hapi says they should be done.

Express is more a raw request handler, letting you do whatever you want, but you have to do it really hard, almost on a per route basis

**Comment by Chalarangelo** [comment]
> you have to do it really hard, almost on a per route basis

@skatcat31 you just described my experience with Express. Which is why I think hapi can be easier to start with (or anything a bit more opinionated). Working on something as barebones as Express is cool, but it takes a lot of work if you are not super familiar with it - I'm not.

**Comment by skatcat31** [comment]
@Chalarangelo [an example](https://github.com/skatcat31/simpleExpressExample) of [my express autoloader](https://github.com/skatcat31/simpleExpress)

I have a LOT of experience with Express and scaffolding it in such ways that makes it extremely extendable, and easy, composable, and contained.

As an example, this is what my app.js files usually look like:

```js
const app = require('simpleexpress')(folder);
```

This crawls the folder and looks for three sub folders:

 - routes
 - plugins
 - middleware

It then loads them into the application. I do need to document it better but I haven't had a chance too...

**Comment by fejes713** [comment]
Yeah, both could be merged somehow.

**Comment by skatcat31** [comment]
Are we still looking at this?

**Comment by fejes713** [comment]
A week ago DigitalOcean agreed to be a sponsor of our project. We got one droplet that will be used to host backend.

So yes, this is still open. I wish we can start implementing this these days but time is tough.

**Comment by flxwu** [comment]
we can all agree on node/Express right?

**Comment by flxwu** [comment]
we can all agree on node/Express right?

**Comment by skatcat31** [comment]
yes I can agree on that

**Comment by Chalarangelo** [comment]
Yep, I agree as it's competent and I am familiar with that stack.

**Comment by skatcat31** [comment]
the question is how do we footprint each individual user so as to keep votes as non game-able as possible?

**Comment by Chalarangelo** [comment]
Two viable options from where I stand:
- IP + browser data to approximate users and use a cookie to store returning visitors, make for a more inclusive system but can be gamed under circumstances.
- Use a 3rd party authorization system, preferrably GitHub, less game-able, but less inclusive, too.

A combination of the two would also be possible, but we will have to weigh votes and build a system to detect fraud.

**Comment by flxwu** [comment]
however let's just start and deal with that later

**Comment by Chalarangelo** [comment]
@flxwu A simple IP+token based implementation sounds like a good start. After all, all of the 30s projects are based on trial and error and we have goofed in a lot of places before. This won't cause any irreversible damage even if the system is abused to death, as we can always wipe the slate clean and start over with the voting. So let's get started on that.

**Comment by skatcat31** [comment]
IP won't work with so much NAT in the real world. As a point in case yesterday my IP address was in the 20.XXX.YYY block and today it's in the 29, and it hasn't actually been 24 hours.

**Comment by Chalarangelo** [comment]
@skatcat31 That's a decent point, my IP changes a lot plus I work in a building with 100+ computers all under the same IP. But we cannot access MAC address in any way or anything else that feels worthwhile, so the only alternative would be to use GitHub's authorization system and only accept verified users. Not a terrible choice, but might cause vote counts to be lower than what we might want. Although, I kinda like this idea, as it will be better for community-building in the long run.

**Comment by skatcat31** [comment]
we could fingerprint: https://arstechnica.com/information-technology/2017/02/now-sites-can-fingerprint-you-online-even-when-you-use-multiple-browsers/

however I like the idea of GitHub integration so that only verified users can vote. This will give us a repeatable and verifiable way to keep track with an already secure login system :wink:

**Comment by fejes713** [comment]
I like the Github idea very much. That way only _real developers_ could vote 😄 

*NOTE: I got a small surprise comming very soon to this project. Expect new category, 50 questions.*
