### ISSUE TITLE
Performance issues on Safari

### ISSUE THREAD

**Issue by atomiks** [fejes713/30-seconds-of-interviews#60]
`Composite paint` is taking 700ms when showing an answer for some reason. Chrome and FF are instant

**Comment by atomiks** [comment]
iOS Safari performance is perfect (iPhone 8+).

What could possibly be wrong with macOS Safari?...

**Comment by skatcat31** [comment]
Safari is such an awkward duck... things that exist everywhere else don't exist in it or are different... Same with Firefox...

You'd think Apple would have created an abstraction layer so that performance would be directly tied to device speed...

**Comment by fejes713** [comment]
@atomiks WWDC is right around the corner, they might tell us!

The good thing is that Safari is MacOS only and most devs use Chrome / Firefox on Macs. I'll check analytics to see how much % are we getting from MacOS & Safari 😉

**Comment by atomiks** [comment]
We should focus on improving performance. I did a Lighthouse audit:

![img](https://i.gyazo.com/ec16089cdbb9122e0c855cd254d50b55.png)
![img](https://i.gyazo.com/c1a134a84b334acbf86bd6e65d25b6ae.png)

Main things I see:

- Server-side rendering so first meaningful paint occurs sooner
- Inline the CSS
- Input latency is horrific (359ms). I will change from conditional rendering to using display block/none to improve filtering speed. "Show answer" performance I'm unsure of yet on Safari as that didn't help.
- Nodes are over 4,000 while the recommended number is <1,500. Since we just display a large list, not sure what can be done here.
- `.Questions-wrapper` should be `li` not `div`
- Color contrast should be increased slightly all over
-

**Comment by skatcat31** [comment]
What parts of the page are hard static and what parts are dynamic(rely on loading content)?

**Comment by atomiks** [comment]
Everything is static.

I think we can generate markdown on build generation and not offload to the client and use memoization as well.

**Comment by skatcat31** [comment]
That's a pretty good idea. Why memoization though?

**Comment by atomiks** [comment]
Sorry, I meant that the current markdown is memoized because it gets called again when filtering. The display block/none technique mitigates the need for that (and so would server-side markdown generation)

**Comment by skatcat31** [comment]
By server side do you mean pre generation of the markdown?

**Comment by fejes713** [comment]
We should definitely take more care about performance. Current loading speeds are not fancy. It takes 2.7s to load 1st layer of the page.

I don't know much about server-side rendering but I guess we can move the hard work of linting to the server and let user load page without needing to do any work on the client side? Are we on the same page, or I am just a bit dumb about this whole performance thing? @atomiks 😄

**Comment by skatcat31** [comment]
@fejes713 @atomiks I would like to clear up what you mean by server here:

- active generation of HTML per request by a remote service
- pre generation during build process so client needs to do minimal parsing before display

**Comment by atomiks** [comment]
The raw extracted string from the `.md` file is what the JSON contains. So we use `marked()` client-side to parse it when they load the page. Rather, we can do that process when we build it instead.

**Comment by jorgebucaran** [comment]
@fejes713 @atomiks I am not overly familiar with your code base yet, but this part caught my attention:

https://github.com/fejes713/30-seconds-of-interviews/blob/ca96d0f37a2c42be4cbb12dcdecfa84ede3230f3/website/js/components/Question.js#L35-L39

It seems that questions and answers are _eagerly_ parsed (with <samp>marked</samp>) during the first render.

https://github.com/fejes713/30-seconds-of-interviews/blob/ca96d0f37a2c42be4cbb12dcdecfa84ede3230f3/website/js/components/Markdown.js#L14-L22

Instead of using CSS to change the visibility of answers, why not use conditional rendering? If my calculations are correct, the answer should only be parsed once (and then cached) when the user clicks Show Answer, and not when the page first loads.

---

This doesn't imply changing your cache mechanism, that part is fine, albeit underutilized at the moment.

**Comment by atomiks** [comment]
> Instead of using CSS to change the visibility of answers, why not use conditional rendering? If my calculations are correct

Conditional rendering is currently used for filtering the questions themselves, but it creates signfiicant performance issues. If we use `display` to toggle the visibility, it seems to render much faster (creating the node once vs. creating it conditionally?)

**Comment by skatcat31** [comment]
it shouldn't render unless it changes DOM... at least it shouldn't. This may be a Safari specific quirk

**Comment by jorgebucaran** [comment]
@atomiks Good points. I'll try to have a look when I find time. I just want to add, that while this is probably **not** the issue, conditional rendering is the correct approach if you want to avoid eagerly parsing markdown.

Offtopic: What about an infinite scroll where we only show a subset of the data? 🤔

**Comment by jorgebucaran** [comment]
@atomiks @fejes713 Like some of you already commented, this appears to be an issue with the layout and rendering (not with the JavaScript), so I started fiddling with the CSS. I don't really know CSS well, but removing `transform: rotateX(180deg)` in <samp>Question.scss</samp> solved the problem.

https://github.com/fejes713/30-seconds-of-interviews/blob/ca96d0f37a2c42be4cbb12dcdecfa84ede3230f3/website/css/components/Question.scss#L95-L99

### Before (slow)
![2018-06-06 15 46 59](https://user-images.githubusercontent.com/56996/41021305-e7eb3cba-69a0-11e8-8963-850372ceb595.gif)

### After (fast)
![2018-06-06 15 46 20](https://user-images.githubusercontent.com/56996/41021301-e63dd878-69a0-11e8-9a24-69fbb294c43e.gif)

**Comment by jorgebucaran** [comment]
EDIT: Leaving the rotateX, but removing the transition also fixes the problem.

https://github.com/fejes713/30-seconds-of-interviews/blob/ca96d0f37a2c42be4cbb12dcdecfa84ede3230f3/website/css/components/Question.scss#L91-L93

**Comment by atomiks** [comment]
Hahah so random. That's an easy fix. Why is the arrow in the after or is that to highlight paint issues?

**Comment by jorgebucaran** [comment]
> to highlight paint issues

Correct. `color: red` FTW.

**Comment by fejes713** [comment]
@jorgebucaran Thank you so much for this one! 😄
