### ISSUE TITLE
Links in the readme are not generating correctly

### ISSUE THREAD

**Issue by skatcat31** [fejes713/30-seconds-of-interviews#62]
The link generation for the readme is broken. Currently broken links are as follows:

# Javascript
1. how-can-you-avoid-callback-hells-js-get-data-function-a-get-more-data-a-function-b-get-more-data-b-function-c-get-more-data-c-function-d-get-more-data-d-function-e
1. how-do-you-clone-an-object-in-java-script
1. how-do-you-compare-two-objects-in-java-script
1. what-is-the-difference-between-the-equality-operators-and
1. what-does-0-1-0-2-0-3-evaluate-to
1. what-is-the-difference-between-the-array-methods-map-and-for-each
1. what-will-the-console-log-in-this-example-js-var-foo-1-var-foobar-function-console-log-foo-var-foo-2-foobar
1. how-does-hoisting-work-in-java-script
1. what-is-the-reason-for-wrapping-the-entire-contents-of-a-java-script-source-file-in-a-function-that-is-immediately-invoked
1. create-a-function-that-masks-a-string-of-characters-with-except-for-the-last-four-4-characters-js-mask-123456789-6789
1. what-is-the-only-value-not-equal-to-itself-in-java-script
1. node-js-uses-a-callback-pattern-in-many-instances-where-if-an-error-were-returned-it-will-pass-it-as-the-first-argument-to-the-callback-what-are-the-advantages-of-this-pattern-js-fs-read-file-file-path-function-err-data-if-err-handle-the-error-the-return-is-important-here-so-execution-stops-here-return-console-log-err-use-the-data-object-console-log-data
1. what-is-the-event-loop-in-node-js
1. does-java-script-pass-by-value-or-by-reference
1. create-a-function-pipe-that-performs-left-to-right-function-composition-by-returning-a-function-that-accepts-one-argument-js-const-square-v-v-v-const-double-v-v-2-const-add-one-v-v-1-const-res-pipe-square-double-add-one-res-3-19-add-one-double-square-3
1. what-is-the-output-of-the-following-code-js-const-a-1-2-3-const-b-1-2-3-const-c-1-2-3-console-log-a-c-console-log-a-b
1. what-does-the-following-function-return-js-function-greet-return-message-hello
1. what-is-the-difference-between-synchronous-and-asynchronous-code-in-java-script
1. what-does-the-following-code-evaluate-to-js-typeof-typeof-0
1. what-are-java-script-data-types
1. what-is-the-purpose-of-java-script-ui-libraries-frameworks-like-react-vue-angular-hyperapp-etc

# HTML
1. Not evaluated yet

# CSS
1. Not evaluated yet

# Node
1. Note evaluated yet

**Comment by flxwu** [comment]
This was fixed in #74dae17
