### ISSUE TITLE
Expertise sorting

### ISSUE THREAD

**Issue by atomiks** [fejes713/30-seconds-of-interviews#65]
A comment was made on Reddit:

>I think splitting the questions into levels was a mistake.
It's the depth of the answer that should differ depending on the level of the candidate.

> A junior should know about closure, an intermediate/senior should know about currying.
> A junior/intermediate should know what a linter is, a senior should know what an AST is.
> A junior should know how to use promises, an intermediate should know the difference between:

>promise.then(a, b)
> promise.then(a).catch(b)

> Junior should have heard about unit testing,
> Intermediate should know how to write test,
> Senior should have setup testing frameworks at their last job.

> I don't think being senior is about knowing quirks of some language,
> It's about having done mistake in the past and being able to spread that knowledge around.

How should we handle expertise divisions? Or should they just be removed altogether? I think they're valuable depending on the role the candidate is interviewing for but not if they're being used improperly.

**Comment by Chalarangelo** [comment]
I think they are ok and they are not all that prominent on the website to be an issue. Add a disclaimer maybe to tell people that they are not always correct or exact and that people with different experience in different fields may find the expertise divison somewhat inaccurate?

**Comment by Chalarangelo** [comment]
We could even go to a rating logic on a scale from 1 to 10, which will be more granular and not use umbrella terms for a lot of difficulty levels.

**Comment by skatcat31** [comment]
I agree that the Redditor has hit upon a problem, but like most intermediate designers they've addressed the wrong problem:

- Our rating system uses incorrect labels that in most contexts means something completely different

When the rating system was devised it was devised with level of 'knowledge of language' versus 'knowledge of implementation' which is vastly different in an interview. We should change them to instead show that it is the difficulty of the knowledge of the question's expected answer, and not of the question itself.

I like @flxwu suggestion

**Comment by fejes713** [comment]
I've noticed this too. Many people complain that they know senior questions while struggle with junior once and so on. 

I don't think we should remove difficulty at all. It is nice to be able to see what belongs where once you know the answer. However, our ranking system might not be accurate so we can use easy, intermediate and hard as @flxwu  suggested? What's your opinion on this @atomiks @Chalarangelo

**Comment by Chalarangelo** [comment]
Easy, intermediate, hard is quite decent, too. I mean Junior questions can be hard but knowledge a senior has. Senior questions can be easy but knowledge a junior might have. Sounds better imho.
