### ISSUE TITLE
Add a new heading for general knowledge and design practices

### ISSUE THREAD

**Issue by skatcat31** [fejes713/30-seconds-of-interviews#69]
We want to move some things out of Javascript/Node and into a more general Programming or Design headers. A big example of this is Big O complexity which is a general computer science concept that doesn't belong to JS and nesting it under JS only makes it confusing.

We should however note in those questions as we move them what language the examples will be in and any caveats thereof.

Otherwise we're going to get dinged pretty hard for 'Why is this Javascript when it applies to X langauge too" or "Why do you have duplicate questions for different languages"(should we support them in an ever changing landscape)

I'd suggest a general `Programming` and `Design` categories to host such questions

**Comment by fejes713** [comment]
For now, I just want to keep this project JavaScript / HTML / CSS and something tightly connected to those I mentioned. However, I do agree with you. We definitely want to separate those that are not so much JS related. We will add them to `general` category, but not yet. Once we come up with more questions and answers for that category we will add it. I don't want a website that has 1 question in each new category 😕

**Comment by skatcat31** [comment]
Fair enough, can't argue with that. When enough are in the general category that can be branched off then I guess we can do it then

**Comment by fejes713** [comment]
Well, I am closing this until we collect way more questions so we can branch them. I will hopefully reopen this in a month and then we can work on it.
