### ISSUE TITLE
`this` keyword question: `myObject.iife()` should be `myObject.iife`

### ISSUE THREAD

**Issue by hznuksco** [fejes713/30-seconds-of-interviews#70]
![1](https://user-images.githubusercontent.com/27288263/40854024-9b4b79de-6602-11e8-9929-1cf0af0a9356.PNG)
![2](https://user-images.githubusercontent.com/27288263/40854039-9f9ed5d0-6602-11e8-9f2e-c3748b11b647.PNG)
myObject.life() maybe myObject.life

**Comment by skatcat31** [comment]
`iife` stands for `immediately-invoked function expression` and is the format of that functional call:

```js
let a = ( function(){ return 1 } )()
a === 1 // true
```

**Comment by atomiks** [comment]
Yes, it should be `myObject.iife` without calling it as a function. Feel free to make a PR for this.
