### ISSUE TITLE
Array.sort() time complexity

### ISSUE THREAD

**Issue by fedemengo** [fejes713/30-seconds-of-interviews#83]
Shouldn't the time complexity of `Array.sort()` be **O(NlogN)** instead of **O(logN)**? In `questions/big-o-notation.md`

**Comment by fejes713** [comment]
Yeah, I think you're right as well. My friend told me the same thing. Feel free to submit PR if you would like to 👍 

Thanks for noticing this 👍

**Comment by skatcat31** [comment]
IF this hasn't been fixed yet it shouldn't be closed. Either we close it with a fix, they close it with a fix, or we put it as 'will not fix'. Otherwise it should stay open since it has not been `closed`(fixed or decided on) just yet

**Comment by fejes713** [comment]
@skatcat31 You're right. Thanks for letting me know! 👍

**Comment by fedemengo** [comment]
@skatcat31 In my local commit there are two more fixes you can integrate into your last fix. See if it's fine for you.

**Comment by atomiks** [comment]
`NlogN` is `3000ms`, no?

**Comment by skatcat31** [comment]
... I wish I had seen that before I tried to remember what base the notation was in... this really has been a long week.
