### ISSUE TITLE
Consider rewording of "Good to hear" section in answers

### ISSUE THREAD

**Issue by ellisken** [fejes713/30-seconds-of-interviews#86]
The phrase "Good to hear" is  confusing for native English speakers on first glance in this application's context. It's typically used in response rather than as a signal to someone that information will follow. The phrase also doesn't convey that the section is essentially a summary of the longer answer's thesis.

I suggest changing the section title to a more apt word or phrase like "In Short" or "Good to know."

**Comment by skatcat31** [comment]
Good to know might be a better header. Thankfully it shouldn't be too hard to change all instances in the snippets. I'll await final decision before doing an awk/sed replace

**Comment by atomiks** [comment]
When I first saw it, "Good to hear" meant "It's also good [for the interviewer] to hear these points". Though maybe I've looked at it too much since.

**Comment by fejes713** [comment]
You might be right actually. I would like to hear feedback from every member of the core team so we can decide if we're going to replace `Good to hear` phrase. Thanks for noticing this!

In Serbian, that phrase means the same as @atomiks said:
>When I first saw it, "Good to hear" meant "It's also good [for the interviewer] to hear these points". Though maybe I've looked at it too much since.

**Comment by skatcat31** [comment]
My opinion on it is that it's "Good to hear[ for the interviewer]" but again developer bias. That may not be obvious to those that come to the site.
