### ISSUE TITLE
the answer is wrong for the question: "How do you compare two objects in JavaScript?"

### ISSUE THREAD

**Issue by chenjigeng** [fejes713/30-seconds-of-interviews#99]
The code can't work by calling
```javascript
isDeepEqual(1, 2)
```
This is my answer:
```javascript
function isDeepEqual(obj1, obj2, testPrototypes = false) {
    if (obj1 === obj2) {
        return true;
    }
    if (type(obj1) === 'Function' && type(obj2) === 'Function') {
        return obj.toString() === obj2.toString();
    }
    if (type(obj1) === 'Date' && type(obj2) === 'Date') {
        return obj1.getTime() === obj2.getTime();
    }
    
    if (type(obj1) !== type(obj2) || type(obj1) !== 'object') {
        return false;
    }

    const prototypesAreEqual = testPrototypes
        ? isDeepEqual(
            Object.getPrototypeOf(obj1),
            Object.getPrototypeOf(obj2),
            true
        )
        : true;

    const obj1Props = Object.getOwnPropertyNames(obj1);
    const obj2Props = Object.getOwnPropertyNames(obj2);

    return (
        obj1Props.length === obj2Props.length &&
        prototypesAreEqual &&
        obj1Props.every(prop => isDeepEqual(obj1[prop], obj2[prop]))
    )
}

function type(obj) {
    return Object.prototype.toString.call(obj);
}

```

**Comment by flxwu** [comment]
Please open a PR if you think the code in the answer should be changed. Thanks! 😊

**Comment by skatcat31** [comment]
i'm going to reopen this to allow for easier discussion from #100

**Comment by chenjigeng** [comment]
yes.and it will return true with { a:1 } amd { a: 2} used as arguments.The code can't work.

**Comment by skatcat31** [comment]
This is a confirmed problem. We might need to add better handling for this.

Or we could just use `JSON.stringify(a) === JSON.stringify(b)` as a short and sloppy...

But like I said it's sloppy and only really applies to POJO(Plain Old JavaScript Object)

**Comment by chenjigeng** [comment]
We can solve it by adding a if statement.You can see my code above.

**Comment by fejes713** [comment]
@chenjigeng thanks for noticing this. The PR is merged. ❤️

**Comment by skatcat31** [comment]
right never reported test results did I... yeah it's working in all cases. Never found an edge case that could be considered a problem except for a SO if I went deep with auto generating object references
